#!/usr/bin/env perl

##############################################################################################
### fixCoord.pl                                                                            ###
##############################################################################################
### Script to process text files generated by SMART. Sometimes coordinates were not        ###
### correctly introduced when doing the recording. This script corrects this type of files ###
### example fixCoord.pl                                                                    ###
##############################################################################################
###OPTIONS                                                                                 ###
###                                                                                        ###
##############################################################################################

